export const denialMockData = [
    {
        id: 1,
        denialId: 'DNL-0456',
        priority: 'high',
        patient: { name: 'John Doe', mrn: '12345' },
        serviceDate: '2024-02-15',
        denialDate: '2024-03-01',
        payer: 'UnitedHealthcare',
        denialReason: 'CO-22: Missing modifier',
        amount: 1200,
        daysLeft: 5,
        status: 'Drafting Appeal',
        linkedAppealId: 'APL-1001',
        notes: ""
    },
    {
        id: 2,
        denialId: 'DNL-0789',
        priority: 'high',
        patient: { name: 'John Doe', mrn: '12345' },
        serviceDate: '2024-02-16',
        denialDate: '2024-03-02',
        payer: 'UnitedHealthcare',
        denialReason: 'CO-16: Claim lacks information',
        amount: 2500,
        daysLeft: 4,
        status: 'Under Review',
        linkedAppealId: 'APL-1002',
        notes: ""
    },
    {
        id: 3,
        denialId: 'DNL-0234',
        priority: 'medium',
        patient: { name: 'Sarah Johnson', mrn: '12346' },
        serviceDate: '2024-02-10',
        denialDate: '2024-02-25',
        payer: 'Aetna',
        denialReason: 'CO-50: Non-covered service',
        amount: 3500,
        daysLeft: 8,
        status: 'Appeal Ready',
        linkedAppealId: null,
        notes: ""
    },
    {
        id: 4,
        denialId: 'DNL-0567',
        priority: 'high',
        patient: { name: 'Sarah Johnson', mrn: '12346' },
        serviceDate: '2024-02-12',
        denialDate: '2024-02-28',
        payer: 'Aetna',
        denialReason: 'CO-97: Payment adjusted',
        amount: 1800,
        daysLeft: 6,
        status: 'Documentation Pending',
        linkedAppealId: 'APL-1003',
        notes: ""
    },
    {
        id: 5,
        denialId: 'DNL-0890',
        priority: 'low',
        patient: { name: 'Sarah Johnson', mrn: '12346' },
        serviceDate: '2024-02-14',
        denialDate: '2024-03-01',
        payer: 'Aetna',
        denialReason: 'CO-18: Duplicate claim',
        amount: 950,
        daysLeft: 12,
        status: 'New',
        linkedAppealId: null,
        notes: ""
    },
    {
        id: 6,
        denialId: 'DNL-0345',
        priority: 'high',
        patient: { name: 'Robert Smith', mrn: '12347' },
        serviceDate: '2024-02-01',
        denialDate: '2024-02-20',
        payer: 'Cigna',
        denialReason: 'CO-11: Diagnosis inconsistent',
        amount: 4200,
        daysLeft: 3,
        status: 'Clinical Review',
        linkedAppealId: 'APL-1004',
        notes: ""
    },
    {
        id: 7,
        denialId: 'DNL-0678',
        priority: 'medium',
        patient: { name: 'Emily Davis', mrn: '12348' },
        serviceDate: '2024-02-05',
        denialDate: '2024-02-22',
        payer: 'Blue Cross',
        denialReason: 'CO-29: Time limit expired',
        amount: 800,
        daysLeft: 15,
        status: 'New',
        linkedAppealId: null,
        notes: ""
    },
    {
        id: 8,
        denialId: 'DNL-0901',
        priority: 'high',
        patient: { name: 'Emily Davis', mrn: '12348' },
        serviceDate: '2024-02-08',
        denialDate: '2024-02-24',
        payer: 'Blue Cross',
        denialReason: 'CO-96: Non-covered charges',
        amount: 2200,
        daysLeft: 2,
        status: 'Urgent Review',
        linkedAppealId: 'APL-1005',
        notes: ""
    },
    {
        id: 9,
        denialId: 'DNL-0123',
        priority: 'medium',
        patient: { name: 'Michael Wilson', mrn: '12349' },
        serviceDate: '2024-02-03',
        denialDate: '2024-02-21',
        payer: 'Humana',
        denialReason: 'CO-251: Medical records missing',
        amount: 3200,
        daysLeft: 7,
        status: 'Gathering Records',
        linkedAppealId: 'APL-1006',
        notes: ""
    },
    {
        id: 10,
        denialId: 'DNL-0432',
        priority: 'high',
        patient: { name: 'Michael Wilson', mrn: '12349' },
        serviceDate: '2024-02-16',
        denialDate: '2024-03-01',
        payer: 'Medicare',
        denialReason: 'CO-197: Precertification absent',
        amount: 2800,
        daysLeft: 4,
        status: 'Pending Provider',
        linkedAppealId: 'APL-1007',
        notes: ""
    }
];

export const appealMockData = [
    {
        id: 'APL-1001',
        linkedDenialId: 'DNL-0456',
        status: { main: 'Under Review', sub: 'Awaiting payer response' },
        assignedTo: { name: 'Dr. Smith', role: 'Coder' },
        submittedDate: '2024-02-15',
        expectedResponseDate: '2024-03-15',
        daysLeft: 5,
        appealReason: 'CO-22: Missing modifier 25',
        payer: 'Medicare',
        amountAppealed: 1500,
        daysSinceSubmission: 12,
        actionsNeeded: 'Attach clinical notes',
        outcome: { status: 'Pending', recoveredAmount: null },
        supportingDocs: ['Appeal Letter', 'Operative Report'],
        successProbability: 75,
        escalationLevel: 1,
        notes: ""
    },
    {
        id: 'APL-1002',
        linkedDenialId: 'DNL-0789',
        status: { main: 'Draft', sub: 'Initial review' },
        assignedTo: { name: 'John Doe', role: 'Billing' },
        submittedDate: '2024-02-25',
        expectedResponseDate: '2024-03-30',
        daysLeft: 15,
        appealReason: 'CO-16: Claim lacks information',
        payer: 'Aetna',
        amountAppealed: 2000,
        daysSinceSubmission: 5,
        actionsNeeded: 'Add prior auth proof',
        outcome: { status: 'Pending', recoveredAmount: null },
        supportingDocs: ['Template'],
        successProbability: 65,
        escalationLevel: 1,
        notes: ""
    },
    {
        id: 'APL-1003',
        linkedDenialId: 'DNL-0567',
        status: { main: 'Under Review', sub: 'Documentation review' },
        assignedTo: { name: 'Sarah Chen', role: 'Clinical' },
        submittedDate: '2024-02-20',
        expectedResponseDate: '2024-03-20',
        daysLeft: 8,
        appealReason: 'CO-97: Payment adjusted',
        payer: 'Aetna',
        amountAppealed: 1800,
        daysSinceSubmission: 10,
        actionsNeeded: 'Review clinical documentation',
        outcome: { status: 'Pending', recoveredAmount: null },
        supportingDocs: ['Medical Records', 'Appeal Letter'],
        successProbability: 82,
        escalationLevel: 1,
        notes: ""
    },
    {
        id: 'APL-1004',
        linkedDenialId: 'DNL-0345',
        status: { main: 'Won', sub: 'Partial approval' },
        assignedTo: { name: 'Dr. Johnson', role: 'Clinical' },
        submittedDate: '2024-02-10',
        expectedResponseDate: '2024-03-10',
        daysLeft: 0,
        appealReason: 'CO-11: Diagnosis inconsistent',
        payer: 'Cigna',
        amountAppealed: 4200,
        daysSinceSubmission: 20,
        actionsNeeded: 'Process recovery',
        outcome: { status: 'Won', recoveredAmount: 3500 },
        supportingDocs: ['Appeal Letter', 'Clinical Notes', 'Approval Notice'],
        successProbability: 100,
        escalationLevel: 1,
        notes: ""
    },
    {
        id: 'APL-1005',
        linkedDenialId: 'DNL-0901',
        status: { main: 'Under Review', sub: 'Escalated to supervisor' },
        assignedTo: { name: 'Maria Garcia', role: 'Appeals' },
        submittedDate: '2024-02-18',
        expectedResponseDate: '2024-03-18',
        daysLeft: 6,
        appealReason: 'CO-96: Non-covered charges',
        payer: 'Blue Cross',
        amountAppealed: 2200,
        daysSinceSubmission: 15,
        actionsNeeded: 'Follow up with payer',
        outcome: { status: 'Pending', recoveredAmount: null },
        supportingDocs: ['Appeal Letter', 'Policy Documentation'],
        successProbability: 70,
        escalationLevel: 2,
        notes: ""
    },
    {
        id: 'APL-1006',
        linkedDenialId: 'DNL-0123',
        status: { main: 'Lost', sub: 'Appeal denied' },
        assignedTo: { name: 'Tom Wilson', role: 'Appeals' },
        submittedDate: '2024-02-05',
        expectedResponseDate: '2024-03-05',
        daysLeft: 0,
        appealReason: 'CO-251: Medical records missing',
        payer: 'Humana',
        amountAppealed: 3200,
        daysSinceSubmission: 25,
        actionsNeeded: 'Prepare second level appeal',
        outcome: { status: 'Lost', recoveredAmount: 0 },
        supportingDocs: ['Appeal Letter', 'Denial Notice'],
        successProbability: 35,
        escalationLevel: 2,
        notes: ""
    },
    {
        id: 'APL-1007',
        linkedDenialId: 'DNL-0432',
        status: { main: 'Under Review', sub: 'Clinical review' },
        assignedTo: { name: 'Dr. Brown', role: 'Clinical' },
        submittedDate: '2024-02-22',
        expectedResponseDate: '2024-03-22',
        daysLeft: 10,
        appealReason: 'CO-197: Precertification absent',
        payer: 'Medicare',
        amountAppealed: 2800,
        daysSinceSubmission: 8,
        actionsNeeded: 'Submit additional documentation',
        outcome: { status: 'Pending', recoveredAmount: null },
        supportingDocs: ['Appeal Letter', 'Prior Auth Documentation'],
        successProbability: 60,
        escalationLevel: 1,
        notes: ""
    }
]; 